### PR TITLE
Removed conflicting or redundant children props

### LINKED ISSUE #2169: BlobProvider type error TS2769
**Describe the bug**
The usage example of `BlobProvider` throw a typescript error
```
<BlobProvider document={MyDoc}>
  {({ blob, url, loading, error }) => {
    // Do whatever you need with blob here
    return <div>There's something going on on the fly</div>;
  }}
</BlobProvider>
```

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Use the example code in a typescript project
2. See error TS2769

**Expected behavior**
No typescript error

**Screenshots**
Sorry, this is in French
```
Aucune surcharge ne correspond à cet appel.
  La surcharge 1 sur 2, '(props: PropsWithChildren<BlobProviderProps> | Readonly<PropsWithChildren<BlobProviderProps>>): BlobProvider', a généré l'erreur suivante.
    Impossible d'assigner le type '({ blob, url, loading, error }: BlobProviderParams) => Element' au type '((params: BlobProviderParams) => ReactNode) & ReactNode'.
      Impossible d'assigner le type '({ blob, url, loading, error }: BlobProviderParams) => Element' au type '((params: BlobProviderParams) => ReactNode) & string'.
        Impossible d'assigner le type '({ blob, url, loading, error }: BlobProviderParams) => Element' au type 'string'.
  La surcharge 2 sur 2, '(props: PropsWithChildren<BlobProviderProps>, context: any): BlobProvider', a généré l'erreur suivante.
    Impossible d'assigner le type '({ blob, url, loading, error }: BlobProviderParams) => Element' au type '((params: BlobProviderParams) => ReactNode) & ReactNode'.ts(2769)
index.d.ts(419, 5): Le type attendu provient de la propriété 'children', qui est déclarée ici sur le type 'IntrinsicAttributes & IntrinsicClassAttributes<BlobProvider> & Readonly<PropsWithChildren<BlobProviderProps>>'
index.d.ts(419, 5): Le type attendu provient de la propriété 'children', qui est déclarée ici sur le type 'IntrinsicAttributes & IntrinsicClassAttributes<BlobProvider> & Readonly<PropsWithChildren<BlobProviderProps>>'
```

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - Browser any
 - React-pdf version 3.1.1

### PR DESCRIPTION
**Pull request by rdennis**
# Purpose

Fixes issues with conflicting or redundant `children` type definitions. 

# Issue History

I've included some history here to explain the issue as I understand it, what has been done to address it, and what is needed to fix the outstanding issues.

## Conflicting `children`

As mentioned in #1798, the release of react@18 [removed the implicit `children` prop](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210). It appears that the [types-react-codemod](https://github.com/eps1lon/types-react-codemod#readme) was used which added `React.PropsWithChildren<>` to all components. While this works for the majority of components, there are a few (`BlobProvider`, `PDFViewer`, and `PDFDownloadLink`) which have more specific requirements for `children`. The addition of `React.PropsWithChildren` with the existing definitions of `children` for these components causes issues like #2169. 

## Redundant `children`

In #1825 a few definitions of `children?: React.ReactNode` were added which became redundant when `React.PropsWithChildren` was added to the components that use those prop types. In these cases I just removed the redundant `children` definition and left the `React.PropsWithChildren`.

Fixes #2169

### CODE REVIEW

File: packages/renderer/index.d.ts [hunk 1]
```diff
@@ -215,7 +210,7 @@ declare namespace ReactPDF {
     children: string;
   }
 
-  class Note extends React.Component<React.PropsWithChildren<NoteProps>> {}
+  class Note extends React.Component<NoteProps> {}
```
Comment (rdennis) [inline packages/renderer/index.d.ts:213]: While the current type does limit `children` to a single `string`, the error message is convoluted.
> No overload matches this call.
  Overload 1 of 2, '(props: PropsWithChildren\<NoteProps> | Readonly\<PropsWithChildren\<NoteProps>>): Note', gave the following error.
    Type 'Element' is not assignable to type 'string & ReactNode'.
      Type 'ReactElement\<any, any>' is not assignable to type 'string & ReactPortal'.
        Type 'ReactElement\<any, any>' is not assignable to type 'string'.
  Overload 2 of 2, '(props: PropsWithChildren\<NoteProps>, context: any): Note', gave the following error.
    Type 'Element' is not assignable to type 'string & ReactNode'.

vs the new error
> No overload matches this call.
  Overload 1 of 2, '(props: NoteProps | Readonly\<NoteProps>): Note', gave the following error.
    Type 'Element' is not assignable to type 'string'.
  Overload 2 of 2, '(props: NoteProps, context: any): Note', gave the following error.
    Type 'Element' is not assignable to type 'string'.

**Comment by jeetiss** [comment]
@rdennis thanks for your contribution! Could you please remove `React.PropsWithChildren` type for `Canvas` and `Image` components because they don't have children?

**Comment by rdennis** [comment]
> @rdennis thanks for your contribution! Could you please remove `React.PropsWithChildren` type for `Canvas` and `Image` components because they don't have children?

I think that's a very good idea, but it does cause a possibly annoying issue where even a single whitespace will cause an error.

```tsx
{/* Error */}
<Image // Property 'children' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Image> & Readonly<ImageProps>)'.
    source={''}>
</Image>
<Image // Property 'children' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Image> & Readonly<ImageProps>)'.
    source={''}> </Image>
{/*             ^ Notice the space */}

{/* Valid */}
<Image
    source={''}></Image>
<Image
    source={''} />
```

That is probably reasonable, but could be annoying for consumers who didn't use self-closing tags for `Image` or `Canvas`. I have a commit ready to push up if that change is acceptable. 

> and one other thing: Could you please run `yarn changeset` to generate a change, that will be used to release this patch?

Should I run this with every commit, or just once with the final changes? I didn't see anything about it in the [contributing doc](https://github.com/diegomura/react-pdf/blob/master/.github/CONTRIBUTING.md).
