### PR TITLE
fix: TypeError when returning fragments or arrays from render prop

### LINKED ISSUE #1872: Error when returning an array on render prop
**Describe the bug**

When I try something like:
```jsx
<View
  render={({ pageNumber }) => (
    items.map(item => <Text>{item.label}, page: {pageNumber}</Text>)
  )}
/>
```

React Pdf throws an exception

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Create a document with react PDF
2. Pass the render prop and return an array from there
3. It throwa

Codesanbox showing the errro: https://codesandbox.io/s/objective-greider-i5p544

**Expected behavior**
It should work normally as if the array was passed as children.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Browser Chrome
 - React-pdf version v2.1.2

### PR DESCRIPTION
**Pull request by jasnross**
This change fixes #1872 by supporting fragments and arrays as valid nodes to be returned from `render`. It also adds support for nested dynamic components.

### CODE REVIEW

File: packages/layout/src/node/createInstances.js [hunk 1]
```diff
@@ -0,0 +1,59 @@
+import { castArray } from '@react-pdf/fns';
```
Comment (jasnross) [inline packages/layout/src/node/createInstances.js:1]: It looks like a new file in the diff here, but this is actually just an edit/rename of `createInstance.js`. Wasn't sure about renaming it but ultimately I thought it felt better with a new name since it now always returns an array of created element instances.
